### ISSUE TITLE
How to open above the input?

### ISSUE THREAD

**Issue by mk-pmb** [nescalante/bonanza#22]
Hi! In my use case, the page is scrolled so that the input field is close to the bottom of the screen. How do I make bonanza open its suggestions above the input field in this case?

**Comment by mk-pmb** [comment]
In case it helps anyone, my current workaround is

```css
form .row.bonanza-open-atop .bz-container { top: auto !important; bottom: 100%; }
```
